export const verbs = [
  "embark upon",
  "explore",
  "venture into",
  "ascend through",
  "navigate",
  "uncover",
  "reveal",
  "survey",
  "probe",
  "delve into",
  "chart",
  "conquer",
  "pursue",
  "venture forth",
  "unravel",
  "discover",
  "forge through",
  "illuminate",
  "bring to light",
  "advance",
  "expand",
  "traverse",
  "journey into",
  "reach",
  "pierce",
  "dive into",
  "explore the depths",
  "launch towards",
  "engage",
  "seek",
  "attain",
  "expand horizons",
  "reach beyond",
  "achieve",
  "unearth",
  "ascend",
  "orbit",
  "reveal secrets of",
  "delve into mysteries of",
  "unfold",
  "surpass",
  "unlock",
  "harness",
  "venture boldly into",
  "chart the unknown",
  "push boundaries of",
  "explore far reaches of",
  "probe depths of",
  "explore realms of",
  "extend",
  "cross",
  "transcend",
  "emerge through",
  "journey beyond",
  "soar across",
  "claim",
  "capture",
  "survey expanses of",
  "examine",
  "decode",
  "test limits of",
  "roam",
  "observe",
  "discover wonders of",
  "push to",
  "explore mysteries of",
  "seek out",
  "discover new realms",
  "experience",
  "brave the cosmos of",
  "plunge into",
  "expand understanding of",
  "research",
  "study",
  "envision",
  "transcend limits of",
  "go beyond",
  "forge new paths in",
  "navigate unknown",
  "observe outer realms of",
  "breakthrough",
  "decode cosmos",
  "chart the universe",
  "expand into",
  "explore edges of",
  "embrace",
  "face",
  "claim uncharted",
  "pursue cosmic",
  "transcend known",
  "study celestial",
  "seek interstellar",
  "harness energy of",
  "venture into stars",
];
