export const locations = [
  "at the edge of the universe",
  "within the Milky Way",
  "in the Andromeda galaxy",
  "in the depths of a black hole",
  "on a distant exoplanet",
  "in the void of space",
  "beyond the stars",
  "in the cosmos",
  "among the asteroids",
  "within the Orion Nebula",
  "in the realms of dark matter",
  "near the event horizon",
  "through cosmic rays",
  "within the Helix Nebula",
  "on the surface of Mars",
  "on a comet's tail",
  "in the light of the supernova",
  "within the Pleiades cluster",
  "in the spiral arms of the galaxy",
  "in the core of a neutron star",
  "through the Oort cloud",
  "in the Kuiper belt",
  "in intergalactic space",
  "on a red dwarf planet",
  "in the Horsehead Nebula",
  "near the galactic center",
  "within a photon storm",
  "on the edge of a quasar",
  "on the rings of Saturn",
  "at the edge of a galaxy",
  "amidst the cosmic dust",
  "near the heart of the cosmos",
  "in the cosmic web",
  "on the verge of a wormhole",
  "near the edge of the observable universe",
  "among the star clusters",
  "in the vastness of the cosmic ocean",
  "in the outermost spiral",
  "beyond Alpha Centauri",
  "on the surface of Europa",
  "within the Crab Nebula",
  "on the shores of Titan",
  "amidst the dark energy",
  "within a pulsar’s beams",
  "among the galactic filaments",
  "within the cosmic background",
  "in a far-flung nebula",
  "on a moon of Jupiter",
  "at the edge of a collapsing star",
  "near the magnetosphere",
  "in the distant cosmos",
  "on a rogue planet",
  "near the speed of light",
  "within an interstellar cloud",
  "in the glare of a pulsar",
  "on the event horizon",
  "at the brink of space-time",
  "amidst cosmic winds",
  "within a collapsing galaxy",
  "amidst dark energy currents",
  "within an aurora of gas",
  "on the far side of the moon",
  "in a nebula-shrouded realm",
  "on an asteroid belt",
  "within a gravity field",
  "within the great void",
  "amidst swirling galaxies",
  "in an unexplored system",
  "at the solar edge",
  "near the cosmic boundary",
  "in a field of comets",
  "amidst quantum particles",
  "through cosmic voids",
  "amongst superclusters",
  "near the outer limits",
  "within the depths of the unknown",
  "through the intergalactic stretch",
];
