export const nouns = [
  "mission",
  "objective",
  "exploration",
  "quest",
  "journey",
  "expedition",
  "venture",
  "ascension",
  "research",
  "endeavor",
  "challenge",
  "odyssey",
  "unveiling",
  "discovery",
  "operation",
  "adventure",
  "chronicle",
  "expedition",
  "voyage",
  "pursuit",
  "cosmic voyage",
  "stellar quest",
  "orbital task",
  "galactic duty",
  "astro-mission",
  "universal exploration",
  "light-bound journey",
  "cosmos mission",
  "galaxy trek",
  "planetary expedition",
  "nebular task",
  "warp-speed objective",
  "celestial journey",
  "solar task",
  "interstellar journey",
  "universe-spanning pursuit",
  "mission to infinity",
  "quasar exploration",
  "event-horizon operation",
  "intergalactic journey",
  "space venture",
  "mission to the stars",
  "quest for knowledge",
  "gravity-bound task",
  "photon pursuit",
  "pulsar quest",
  "orbit-bound duty",
  "celestial odyssey",
  "quantum operation",
  "time-traveling expedition",
  "void-crossing mission",
  "dark-matter exploration",
  "star-bound odyssey",
  "lunar journey",
  "astral pursuit",
  "nebula-bound mission",
  "gravity-riding operation",
  "plasma-venturing objective",
  "cosmic task",
  "solar orbit",
  "stellar task",
  "light-bound voyage",
  "supernova journey",
  "red-dwarf mission",
  "black-hole journey",
  "universal discovery",
  "nova exploration",
  "planet-bound journey",
  "quantum leap",
  "space-time quest",
  "dark-energy pursuit",
  "intergalactic adventure",
  "mission to the void",
  "orbit-bound discovery",
  "stellar passage",
  "gravity-bending journey",
  "universal leap",
  "space pursuit",
  "cosmic ascent",
  "time-loop venture",
  "quasar journey",
  "nebular quest",
  "black-hole exploration",
  "time-warp mission",
  "astro-quest",
  "gravity-lock task",
  "exoplanet journey",
  "quantum task",
  "star-bound leap",
  "galactic ascent",
  "stellar exploration",
  "cosmic journey",
  "planet venture",
];
